/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.39
 * Generated at: 2019-09-06 02:23:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jdbcbean;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class memberPro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>회원가입 확인</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
request.setCharacterEncoding("utf-8"); 
      out.write('\r');
      out.write('\n');
      jdbcbean.MemberBean mb = null;
      mb = (jdbcbean.MemberBean) _jspx_page_context.getAttribute("mb", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (mb == null){
        mb = new jdbcbean.MemberBean();
        _jspx_page_context.setAttribute("mb", mb, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("mb"), request);
      out.write("\t\t\t\r\n");
      jdbcbean.MemberDBbean mdb = null;
      mdb = (jdbcbean.MemberDBbean) _jspx_page_context.getAttribute("mdb", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (mdb == null){
        mdb = new jdbcbean.MemberDBbean();
        _jspx_page_context.setAttribute("mdb", mdb, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
 mdb.insert(mb); 
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("mb"), request);
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("<body bgcolor=\"#FFFFCC\">\r\n");
      out.write("\t\t<table width=\"80%\" align=\"center\" cellspacing=\"0\" cellpadding=\"5\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"center\" valign=\"middle\" bgcolor=\"#FFFFCC\">\r\n");
      out.write("\t\t\t\t<table width=\"90%\" border=1 cellspacing=\"0\" cellspacing=\"2\" align=\"center\">\r\n");
      out.write("\t\t\t\t<form name=regForm method=post action=\"update.jsp\">\t\r\n");
      out.write("\t\t\t\t\t<tr align=center bgcolor=\"#996600\">\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\"><font color=\"#FFFFFF\"><b>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jdbcbean.MemberBean)_jspx_page_context.findAttribute("mb")).getId())));
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t회원님의 정보입니다.</b></font></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=20%>아이디</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jdbcbean.MemberBean)_jspx_page_context.findAttribute("mb")).getId())));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>패스워드</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jdbcbean.MemberBean)_jspx_page_context.findAttribute("mb")).getPwd())));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>이름</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jdbcbean.MemberBean)_jspx_page_context.findAttribute("mb")).getName())));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>주민등록번호</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jdbcbean.MemberBean)_jspx_page_context.findAttribute("mb")).getNum1())));
      out.write('-');
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jdbcbean.MemberBean)_jspx_page_context.findAttribute("mb")).getNum2())));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>이메일</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jdbcbean.MemberBean)_jspx_page_context.findAttribute("mb")).getEmail())));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>전화번호</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jdbcbean.MemberBean)_jspx_page_context.findAttribute("mb")).getPhone())));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>우편번호</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jdbcbean.MemberBean)_jspx_page_context.findAttribute("mb")).getZipcode())));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>주소</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jdbcbean.MemberBean)_jspx_page_context.findAttribute("mb")).getAddress())));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>직업</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jdbcbean.MemberBean)_jspx_page_context.findAttribute("mb")).getJob())));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=2><center><input type=submit value=\"회원 정보 수정\"></center></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\t<input type=hidden name=id value=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((jdbcbean.MemberBean)_jspx_page_context.findAttribute("mb")).getId())));
      out.write("\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
